import { useEffect, useState } from "react";
import { Printer, RefreshCw } from "lucide-react";
import QRCode from "qrcode";

const initial = { boxQr: "BOX-RJ-260827-00482", sn: "SN-RJ-260827-00482", material: "IC-DRAM-8G", batch: "LOT-260826-A17", quantity: "2400 PCS", recordId: "MSD-482", place: "SMT-01线边", msl: "MSL 3", openedAt: "2026-08-27 07:35", closedAt: "未封箱", openDuration: "2h 15m", remaining: "45h 20m", status: "开封中 · 正常" };

export function MsLabelPrintingPage() {
  const [form, setForm] = useState(initial);
  const [qr, setQr] = useState("");
  useEffect(() => { void QRCode.toDataURL(`BOX_QR|${form.boxQr}|${form.recordId}|${form.batch}`, { width: 180, margin: 1, errorCorrectionLevel: "M" }).then(setQr); }, [form.boxQr, form.recordId, form.batch]);
  const update = (key: keyof typeof initial, value: string) => setForm(prev => ({ ...prev, [key]: value }));
  return <section className="surface-panel ms-label-print-page">
    <div className="section-header" style={{ marginBottom: 16 }}><div><h3 style={{ margin: 0 }}>MS标签打印</h3><p style={{ margin: "4px 0 0", fontSize: 12 }}>打印开封后物料标签，标识SN、批次、数量、ID、位置与剩余Floor Life。</p></div><div style={{ display: "flex", gap: 8 }}><button className="btn-ghost" onClick={() => setForm(initial)}><RefreshCw size={14} /> 重置样例</button><button className="btn-primary" onClick={() => window.print()}><Printer size={14} /> 打印标签</button></div></div>
    <div style={{ display: "grid", gridTemplateColumns: "minmax(320px, 1fr) 380px", gap: 20, alignItems: "start" }}>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>{([ ["boxQr", "箱QR编码"], ["sn", "SN / 序列号"], ["material", "物料编码"], ["batch", "批次"], ["quantity", "数量"], ["recordId", "MSD记录ID"], ["place", "位置"], ["msl", "MSL等级"], ["openedAt", "开封时间"], ["closedAt", "封箱时间"], ["openDuration", "已开封时长"], ["remaining", "剩余Floor Life（时/分）"], ["status", "状态"] ] as [keyof typeof initial, string][]).map(([key, label]) => <label key={key} style={{ display: "flex", flexDirection: "column", gap: 5, fontSize: 12, color: "var(--muted)" }}>{label}<input className="form-input" value={form[key]} onChange={e => update(key, e.target.value)} /></label>)}</div>
      <div style={{ background: "#fff", border: "1px solid #d0d5dd", borderRadius: 8, padding: 18, color: "#101828" }}><div style={{ display: "flex", justifyContent: "space-between", borderBottom: "2px solid #101828", paddingBottom: 10, marginBottom: 12 }}><strong style={{ fontSize: 18 }}>MSD MATERIAL</strong><strong style={{ fontSize: 18 }}>{form.msl}</strong></div><div style={{ textAlign: "center", margin: "12px 0" }}>{qr && <img src={qr} alt="MS箱QR" style={{ width: 150, height: 150 }} />}<div style={{ fontFamily: "monospace", fontSize: 11, marginTop: 5 }}>BOX QR: {form.boxQr}</div></div><div style={{ fontFamily: "monospace", fontSize: 14, fontWeight: 700, textAlign: "center", borderBottom: "1px solid #d0d5dd", paddingBottom: 10, wordBreak: "break-all" }}>{form.sn}</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "7px 14px", marginTop: 12, fontSize: 12 }}><span>物料 <b>{form.material}</b></span><span>批次 <b>{form.batch}</b></span><span>数量 <b>{form.quantity}</b></span><span>ID <b>{form.recordId}</b></span><span>位置 <b>{form.place}</b></span><span>开封 <b>{form.openedAt}</b></span><span>封箱 <b>{form.closedAt}</b></span><span>已开封 <b>{form.openDuration}</b></span><span>剩余 <b style={{ color: "#b42318" }}>{form.remaining}</b></span><span>状态 <b>{form.status}</b></span></div><div style={{ marginTop: 14, paddingTop: 8, borderTop: "1px dashed #98a2b3", fontSize: 10, color: "#667085" }}>扫码查看箱级MSD追溯记录 · 超时禁止上线</div></div>
    </div>
    <style>{`@media print { body * { visibility: hidden !important; } .ms-label-print-page, .ms-label-print-page * { visibility: visible !important; } .ms-label-print-page { position: absolute; left: 0; top: 0; width: 100%; border: 0 !important; } .ms-label-print-page > .section-header, .ms-label-print-page > div:first-of-type { display: none !important; } .ms-label-print-page > div:last-of-type { display: block !important; } .ms-label-print-page > div:last-of-type > div:first-child { display: none !important; } .ms-label-print-page > div:last-of-type > div:last-child { width: 360px; margin: 0 auto; } }`}</style>
  </section>;
}
