import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, RefreshCw, Search, Send } from "lucide-react";
import type { Locale } from "../../../../packages/shared-types/src/factory";
import { docApi, wmsApi, type DocListItem } from "../api/wms";

const C={
  "zh-CN":{title:"补料与工单物料对账",sub:"补料必须引用原始领料单；差异必须说明并审批",wo:"工单号",query:"查询",doc:"补料单",status:"状态",origin:"原领料单",material:"物料",required:"需求",available:"可用",shortage:"短缺",issued:"发料",consumed:"消耗",returned:"退料",difference:"批准差异",balanced:"平衡",unbalanced:"不平衡",create:"提交补料申请",qty:"数量",reason:"原因",refresh:"刷新",none:"暂无数据",requisition:"原领料单ID"},
  "vi-VN":{title:"Bổ sung và đối soát vật tư",sub:"Bổ sung phải tham chiếu phiếu lĩnh gốc; chênh lệch cần giải trình và duyệt",wo:"Lệnh SX",query:"Tra cứu",doc:"Phiếu bổ sung",status:"Trạng thái",origin:"Phiếu lĩnh gốc",material:"Vật tư",required:"Nhu cầu",available:"Khả dụng",shortage:"Thiếu",issued:"Đã cấp",consumed:"Tiêu hao",returned:"Trả lại",difference:"Chênh lệch duyệt",balanced:"Cân bằng",unbalanced:"Lệch",create:"Gửi yêu cầu bổ sung",qty:"Số lượng",reason:"Lý do",refresh:"Làm mới",none:"Không có dữ liệu",requisition:"ID phiếu lĩnh gốc"},
  "en-US":{title:"Replenishment and WO material reconciliation",sub:"Replenishment must reference the original requisition; differences require explanation and approval",wo:"Work order",query:"Query",doc:"Replenishment",status:"Status",origin:"Original requisition",material:"Material",required:"Required",available:"Available",shortage:"Shortage",issued:"Issued",consumed:"Consumed",returned:"Returned",difference:"Approved difference",balanced:"Balanced",unbalanced:"Unbalanced",create:"Submit replenishment",qty:"Quantity",reason:"Reason",refresh:"Refresh",none:"No data",requisition:"Original requisition ID"},
} as const;

export function WmsReplenishments({locale}:{locale:Locale}){
  const c=C[locale];const [items,setItems]=useState<DocListItem[]>([]);const [wo,setWo]=useState("");
  const [shortages,setShortages]=useState<Array<Record<string,unknown>>>([]);const [recon,setRecon]=useState<Array<Record<string,unknown>>>([]);
  const [balanced,setBalanced]=useState<boolean|null>(null);const [message,setMessage]=useState("");
  const [form,setForm]=useState({originalRequisitionId:"",materialCode:"",qty:"",reasonCode:"PROCESS_LOSS"});
  const load=useCallback(async()=>{try{setItems((await docApi.replenishment.list({pageSize:50})).items);}catch(error){setMessage(error instanceof Error?error.message:String(error));}},[]);
  useEffect(()=>{void load();},[load]);
  const inspect=async()=>{if(!wo.trim())return;try{const [s,r]=await Promise.all([wmsApi.getWorkOrderMaterialShortages(wo.trim()),wmsApi.getWorkOrderMaterialReconciliation(wo.trim())]);setShortages(s.items);setRecon(r.items);setBalanced(r.balanced);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:String(error));}};
  const create=async()=>{try{await wmsApi.createReplenishmentRequest({workOrderCode:wo.trim(),originalRequisitionId:Number(form.originalRequisitionId),materialCode:form.materialCode.trim(),qty:Number(form.qty),reasonCode:form.reasonCode,requestor:"MES-WMS"});setMessage(c.create+" ✓");await load();await inspect();}catch(error){setMessage(error instanceof Error?error.message:String(error));}};
  return <div className="screen-stack"><section className="surface-panel"><div className="section-header"><div><h2>{c.title}</h2><p>{c.sub}</p></div><button className="action-button" onClick={()=>void load()}><RefreshCw size={14}/>{c.refresh}</button></div>
    <div className="toolbar"><input value={wo} onChange={e=>setWo(e.target.value)} placeholder={c.wo}/><button className="action-button" onClick={()=>void inspect()}><Search size={14}/>{c.query}</button>{balanced!==null&&<span className={`badge badge-${balanced?"ok":"danger"}`}>{balanced?c.balanced:c.unbalanced}</span>}</div>{message&&<p style={{color:message.includes("✓")?"var(--ok)":"var(--danger)"}}>{message}</p>}</section>
    <section className="surface-panel"><div className="section-header"><h3><AlertTriangle size={16}/> {c.shortage}</h3></div><div className="table-shell"><table><thead><tr><th>{c.material}</th><th>{c.required}</th><th>{c.available}</th><th>{c.shortage}</th></tr></thead><tbody>{shortages.length?shortages.map((r,i)=><tr key={i}><td>{String(r.materialCode)}</td><td>{String(r.requiredQty)}</td><td>{String(r.availableQty)}</td><td style={{color:"var(--danger)"}}>{String(r.shortageQty)}</td></tr>):<tr><td colSpan={4}>{c.none}</td></tr>}</tbody></table></div></section>
    <section className="surface-panel"><div className="section-header"><h3>{c.create}</h3></div><div className="toolbar"><input placeholder={c.requisition} value={form.originalRequisitionId} onChange={e=>setForm({...form,originalRequisitionId:e.target.value})}/><input placeholder={c.material} value={form.materialCode} onChange={e=>setForm({...form,materialCode:e.target.value})}/><input placeholder={c.qty} type="number" value={form.qty} onChange={e=>setForm({...form,qty:e.target.value})}/><select value={form.reasonCode} onChange={e=>setForm({...form,reasonCode:e.target.value})}><option value="PROCESS_LOSS">PROCESS_LOSS</option><option value="LOT_REJECTED">LOT_REJECTED</option><option value="DAMAGE">DAMAGE</option><option value="COUNT_DIFFERENCE">COUNT_DIFFERENCE</option></select><button className="action-button" onClick={()=>void create()}><Send size={14}/>{c.create}</button></div></section>
    <section className="surface-panel"><div className="section-header"><h3>{c.title}</h3></div><div className="table-shell"><table><thead><tr><th>{c.material}</th><th>{c.required}</th><th>{c.issued}</th><th>{c.consumed}</th><th>{c.returned}</th><th>{c.difference}</th><th>{c.status}</th></tr></thead><tbody>{recon.length?recon.map((r,i)=><tr key={i}><td>{String(r.material_code)}</td><td>{String(r.required_qty)}</td><td>{String(r.issued_qty)}</td><td>{String(r.consumed_qty)}</td><td>{String(r.returned_qty)}</td><td>{String(r.approved_difference_qty)}</td><td><span className={`badge badge-${r.balanced?"ok":"danger"}`}>{r.balanced?c.balanced:c.unbalanced}</span></td></tr>):<tr><td colSpan={7}>{c.none}</td></tr>}</tbody></table></div></section>
    <section className="surface-panel"><div className="table-shell"><table><thead><tr><th>{c.doc}</th><th>{c.wo}</th><th>{c.origin}</th><th>{c.status}</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{String((item as any).doc_no)}</td><td>{String((item as any).work_order_code??"—")}</td><td>{String((item as any).original_requisition_id??"—")}</td><td><span className="badge badge-info">{item.status}</span></td></tr>)}</tbody></table></div></section></div>;
}
