import {useCallback,useEffect,useState} from 'react';
type Row={shortageId:number;sourceStation:string;destinationStation:string;batchId?:string;expectedCount:number;actualCount:number;
 missingSns?:string[];reasonCode?:string;reasonDetail?:string;status:string;detectedAt:string;alarmAcknowledgedAt?:string};
type PassReturn={returnId:number;shortageId?:number;sourceStation:string;destinationStation:string;batchId?:string;sns:string[];quantity:number;reason:string;status:string;requestedAt:string;receivedAt?:string};
const reasons=[['TEST_USE','测试占用'],['IN_TRANSFER','转移途中'],['TEMP_STORAGE','暂存'],['REPAIR_QUALITY_HOLD','维修/品质扣留'],['SCRAP_PENDING','报废申请'],['OTHER','其他']];
export function PassShortageManagement(){
 const[rows,setRows]=useState<Row[]>([]);const[returns,setReturns]=useState<PassReturn[]>([]);const[msg,setMsg]=useState('');
 const refresh=useCallback(async()=>{const [r,pr]=await Promise.all([fetch('/api/station/pass-shortages'),fetch('/api/station/pass-returns')]);const d=await r.json();if(!r.ok)throw new Error(d?.message||`HTTP ${r.status}`);setRows(d.items||[]);if(pr.ok)setReturns((await pr.json()).items||[])},[]);
 useEffect(()=>{refresh().catch(e=>setMsg(String(e)));const t=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(t)},[refresh]);
 const explain=async(row:Row)=>{const reasonCode=window.prompt(`缺失原因代码：\n${reasons.map(x=>x.join(' = ')).join('\n')}`,row.reasonCode||'TEST_USE');if(!reasonCode)return;
  const reasonDetail=window.prompt('请输入详细说明（用途、当前位置、责任人、预计返回时间等）',row.reasonDetail||'');if(!reasonDetail)return;
  const r=await fetch(`/api/station/pass-shortages/${row.shortageId}/explain`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reasonCode,reasonDetail,reportedBy:'MES'})});if(!r.ok)setMsg((await r.json())?.message||'操作失败');await refresh()};
 const action=async(row:Row,kind:'acknowledge-alarm'|'resolve')=>{const r=await fetch(`/api/station/pass-shortages/${row.shortageId}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)setMsg((await r.json())?.message||'操作失败');await refresh()};
 const createReturn=async(row:Row)=>{const raw=window.prompt('返还SN（多个SN用逗号分隔）',(row.missingSns||[]).join(','));if(!raw)return;const reason=window.prompt('返还原因及物品当前位置',row.reasonDetail||'');if(!reason)return;const sns=raw.split(/[,\s]+/).filter(Boolean);
  const r=await fetch('/api/station/pass-returns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({shortageId:row.shortageId,sourceStation:row.destinationStation,destinationStation:row.sourceStation,batchId:row.batchId,sns,reason,requestedBy:'MES'})});if(!r.ok)setMsg((await r.json())?.message||'申请失败');await refresh()};
 const approveReturn=async(row:PassReturn)=>{const r=await fetch(`/api/station/pass-returns/${row.returnId}/approve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approvedBy:'MES'})});if(!r.ok)setMsg((await r.json())?.message||'批准失败');await refresh()};
 return <div className="surface-panel" style={{padding:18}}><h2>PASS数量短缺管理 / PASS Shortage Management</h2>
  <p>前站出、后站入必须守恒。填写原因只解释短缺，不会自动关闭；补齐或批准核销后才能完成。</p>{msg&&<div style={{color:'#fbbf24'}}>{msg}</div>}
  <div style={{overflow:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['时间','整盘/SN','前站','后站','应入','实入','短缺','缺失SN','原因','说明','状态','操作'].map(h=><th key={h} style={{padding:8,textAlign:'left',borderBottom:'1px solid #475569'}}>{h}</th>)}</tr></thead>
  <tbody>{rows.map(x=><tr key={x.shortageId} style={{background:x.status!=='RESOLVED'&&!x.alarmAcknowledgedAt?'#7f1d1d33':undefined}}><td>{new Date(x.detectedAt).toLocaleString()}</td><td>{x.batchId||'-'}</td><td>{x.sourceStation}</td><td>{x.destinationStation}</td><td>{x.expectedCount}</td><td>{x.actualCount}</td><td><b>{x.expectedCount-x.actualCount}</b></td><td>{x.missingSns?.join(', ')||'-'}</td><td>{reasons.find(r=>r[0]===x.reasonCode)?.[1]||x.reasonCode||'待说明'}</td><td>{x.reasonDetail||'-'}</td><td>{x.status}</td><td style={{whiteSpace:'nowrap'}}><button onClick={()=>explain(x)}>填写原因</button> {x.status!=='RESOLVED'&&!x.alarmAcknowledgedAt&&<button onClick={()=>action(x,'acknowledge-alarm')}>解除声光报警</button>} {x.status!=='RESOLVED'&&<button onClick={()=>createReturn(x)}>申请返还</button>}</td></tr>)}</tbody></table></div>
  <h3>PASS返还手续 / PASS Return Workflow</h3><div style={{overflow:'auto'}}><table style={{width:'100%'}}><thead><tr>{['申请','短缺单','SN','从','返回','数量','原因','状态','操作'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{returns.map(x=><tr key={x.returnId}><td>{x.returnId}</td><td>{x.shortageId||'-'}</td><td>{x.sns.join(', ')}</td><td>{x.sourceStation}</td><td>{x.destinationStation}</td><td>{x.quantity}</td><td>{x.reason}</td><td>{x.status}</td><td>{x.status==='PENDING_MES_APPROVAL'?<button onClick={()=>approveReturn(x)}>MES批准并生成交工单</button>:x.status==='WAITING_RECEIPT'?'等待返回工位扫码':'已完成'}</td></tr>)}</tbody></table></div>
 </div>;
}
