import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, RefreshCw, RotateCcw, Activity } from "lucide-react";
import { wmsApi } from "../api/wms";

type Locale = "zh-CN" | "en-US" | "vi-VN";
type ReelRow = { id:number; workOrderCode:string; lineCode:string; machineCode:string; channelCode:string; slotNo:string; feederCode:string; materialCode:string; materialNameZh?:string; materialSn:string; lotNo:string; quantity:number; consumedQty:number; remainingQty:number; operator?:string; status:string; boundAt?:string; unboundAt?:string|null; createdAt?:string };

export function SmtReelConsumptionPage({ locale }: { locale: Locale }) {
  const [rows, setRows] = useState<ReelRow[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [safetyMinutes, setSafetyMinutes] = useState(20);
  const load = useCallback(async () => { setLoading(true); try { const result = await wmsApi.getSmtReelConsumption({ safetyMinutes }); setRows(result.items as ReelRow[]); } catch (e) { setMessage(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, [safetyMinutes]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 5000); return () => window.clearInterval(timer); }, [load]);
  const cards = useMemo(() => rows.map(row => { const qty = Math.max(Number(row.quantity) || 0, 0); const remaining = Math.max(Number(row.remainingQty) || qty - (Number(row.consumedQty) || 0), 0); const boundAt = row.boundAt || row.createdAt; const elapsedMin = boundAt ? Math.max((Date.now() - new Date(boundAt).getTime()) / 60000, 1) : 1; const rate = Number(row.consumedQty || 0) / elapsedMin; const minutesLeft = rate > 0 ? remaining / rate : null; const warning = remaining <= 0 ? "CRITICAL" : minutesLeft !== null && minutesLeft <= safetyMinutes ? "CHANGE NOW" : minutesLeft !== null && minutesLeft <= safetyMinutes * 2 ? "PREPARE" : "OK"; return { row, qty, remaining, rate, minutesLeft, warning }; }), [rows, safetyMinutes]);
  const critical = cards.filter(x => x.warning !== "OK").length;
  return <div className="screen-stack"><div className="surface-panel"><div className="section-header"><div><h2><Activity size={20} /> SMT Reel Consumption & Feeder Change</h2><p>MES monitors reel consumption and warns before feeder change affects production.</p></div><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw size={16} /> {loading ? "Refreshing…" : "Refresh"}</button></div><div className="toolbar" style={{ display:"flex", gap:12, alignItems:"end", flexWrap:"wrap" }}><label>Safety warning lead time (minutes)<input type="number" min={1} value={safetyMinutes} onChange={e => setSafetyMinutes(Math.max(1, Number(e.target.value) || 20))} /></label><div className={critical ? "notice warning" : "notice"}>{critical ? `${critical} feeder change warning(s)` : "No feeder changes currently required"}</div></div>{message && <div className="notice error">{message}</div>}</div><div className="surface-panel"><div className="table-wrap"><table><thead><tr><th>Priority</th><th>WO / Line</th><th>Machine / Channel</th><th>Feeder / Reel</th><th>Material</th><th>Loaded</th><th>Consumed</th><th>Remaining</th><th>Est. minutes</th><th>Action</th></tr></thead><tbody>{cards.map(({row,qty,remaining,rate,minutesLeft,warning}) => <tr key={row.id}><td><span style={{ color: warning === "OK" ? "#16a34a" : warning === "PREPARE" ? "#d97706" : "#dc2626", fontWeight:800 }}>{warning}</span></td><td>{row.workOrderCode}<br/><small>{row.lineCode}</small></td><td>{row.machineCode}<br/><small>{row.channelCode}</small></td><td>{row.feederCode}<br/><small>{row.materialSn || row.lotNo}</small></td><td>{row.materialCode}<br/><small>{row.materialNameZh || "—"}</small></td><td>{qty}</td><td>{row.consumedQty || 0}<br/><small>{rate.toFixed(2)}/min</small></td><td style={{ fontWeight:800 }}>{remaining}</td><td>{minutesLeft === null ? "—" : minutesLeft.toFixed(1)}</td><td><button type="button" onClick={() => setMessage(`PDA feeder-change task required for ${row.feederCode} / ${row.materialCode}.`)}><RotateCcw size={14} /> Create PDA task</button></td></tr>)}{!cards.length && <tr><td colSpan={10}>{loading ? "Loading…" : "No active SMT reels"}</td></tr>}</tbody></table></div></div>{critical > 0 && <div className="notice warning"><AlertTriangle size={16} /> Change warnings are based on actual consumed quantity and the adjustable safety lead time. The PDA must scan the replacement reel before removing the active reel.</div>}</div>;
}