import { useCallback, useEffect, useState } from "react";
import { apiClient } from "../api";
import { t } from "../i18n";

type Locale = "zh-CN" | "en-US" | "vi-VN";
interface PdaDomain { id: number; assignmentDate: string; shiftCode: string; positionNo: number; roleCode: string; roleNameEn: string; roleNameZh?: string; employeeCode: string; employeeName: string; lineCode: string; workOrderCode?: string; loadingPermission?: string; validFrom: string; validUntil: string; status: string; }

export function HrPdaDomains({ locale }: { locale: Locale }) {
  const [items, setItems] = useState<PdaDomain[]>([]); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [form, setForm] = useState({ assignmentDate: new Date().toISOString().slice(0,10), shiftCode: "DAY", positionNo: "1", employeeCode: "", lineCode: "", roleCode: "TEAM_LEADER", roleNameEn: "Team Leader", roleNameZh: "班组长", validFrom: "08:00", validUntil: "20:00", loadingPermission: "NONE", workOrderCode: "" });
  const load = useCallback(async () => { setLoading(true); try { setItems(await apiClient.get<PdaDomain[]>("/api/hr/pda-domains")); } catch (e) { setMessage(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const update = (key: string, value: string) => setForm(prev => ({ ...prev, [key]: value }));
  const create = async () => { setLoading(true); setMessage(null); try { await apiClient.post("/api/hr/pda-domains", { ...form, positionNo: Number(form.positionNo), validFrom: `${form.assignmentDate}T${form.validFrom}:00+07:00`, validUntil: `${form.assignmentDate}T${form.validUntil}:00+07:00`, permissionCodes: form.roleCode === "LINE_MANAGER" ? ["line.assign", "line.approve", "material.escalate"] : ["team.view", "attendance.review", "handover.create"] }); setMessage("PDA domain published"); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } };
  const fields = [["assignmentDate","Date"],["shiftCode","Shift"],["employeeCode","Employee ID"],["lineCode","Line"],["positionNo","Position no."],["roleCode","Role code"],["roleNameEn","Role name"],["validFrom","Valid from"],["validUntil","Valid until"]] as const;
  return <div className="screen-stack"><div className="surface-panel"><div className="section-header"><div><h2>{locale === "zh-CN" ? "PDA 管辖域" : locale === "vi-VN" ? "Phạm vi PDA" : "PDA Authorization Domains"}</h2><p>{locale === "zh-CN" ? "HR 管理班组长和线长可操作的人员、线别、班次和有效期" : "HR controls the people, lines, shifts and validity of Team Leader and Line Manager PDA access."}</p></div><button type="button" onClick={() => void load()} disabled={loading}>Refresh</button></div>{message && <div className="notice">{message}</div>}<div className="toolbar" style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 8 }}>{fields.map(([key,label]) => <label key={key}>{label}<input value={form[key]} onChange={e => update(key,e.target.value)} /></label>)}<label>Role<select value={form.roleCode} onChange={e => { const role=e.target.value; update("roleCode",role); update("roleNameEn",role === "LINE_MANAGER" ? "Line Manager" : "Team Leader"); }}><option value="TEAM_LEADER">Team Leader</option><option value="LINE_MANAGER">Line Manager</option></select></label><label>Loading permission<select value={form.loadingPermission} onChange={e => update("loadingPermission",e.target.value)}><option>NONE</option><option>SUPERVISED</option><option>APPROVE</option></select></label><label>WO scope<input value={form.workOrderCode} onChange={e => update("workOrderCode",e.target.value)} placeholder="Optional" /></label><button type="button" onClick={() => void create()} disabled={loading}>Publish PDA domain</button></div></div><div className="surface-panel"><h3>Published domains</h3><div className="table-wrap"><table><thead><tr><th>Date</th><th>Employee</th><th>Role</th><th>Line</th><th>Shift</th><th>WO</th><th>Validity</th><th>Status</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.assignmentDate}</td><td>{item.employeeName} ({item.employeeCode})</td><td>{item.roleNameEn || item.roleCode}</td><td>{item.lineCode}</td><td>{item.shiftCode}</td><td>{item.workOrderCode || "—"}</td><td>{item.validFrom} → {item.validUntil}</td><td>{item.status}</td></tr>)}{!items.length && <tr><td colSpan={8}>{loading ? "Loading…" : "No domains published"}</td></tr>}</tbody></table></div></div></div>;
}